#localhost
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 44b5f22fbae360f5d149
            clientSecret: 2026896e4b5d7cfb9201c6961c470480092c5a1a

##aws
#security:
#  oauth2:
#    client:
#      registration:
#        github:
#          clientId: 6d1434dcb7d80bdcaf58
#          clientSecret: 3958b47ba044fc866e4927b623dcc1f720635771

